Repository CalgaryToSpace/CTS-SAT-1-OBC-Firmware, pull requests merged in 2025-04, with the labels that each got.

#277 EPS: Observe current of each channel and disable them if overcurrent
  docs/Non-Critical_Notes/Configuration_Variables.md
  firmware/Core/Inc/config/configuration.h
  firmware/Core/Inc/eps_drivers/eps_power_management.h
  firmware/Core/Inc/rtos_tasks/rtos_background_upkeep.h
  firmware/Core/Inc/telecommands/eps_telecommands.h
  firmware/Core/Src/config/configuration.c
  firmware/Core/Src/eps_drivers/eps_power_management.c
  firmware/Core/Src/main.c
  firmware/Core/Src/rtos_tasks/rtos_background_upkeep.c
  firmware/Core/Src/telecommands/eps_telecommands.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: pr-please-review, pr-awaiting-testing

#312 Create telecommand: `fs_write_file_hex`
  firmware/Core/Inc/littlefs/littlefs_helper.h
  firmware/Core/Inc/telecommands/lfs_telecommand_defs.h
  firmware/Core/Src/littlefs/littlefs_helper.c
  firmware/Core/Src/telecommands/lfs_telecommand_defs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: pr-awaiting-changes

#305 Create ADCS low power mode telecommand
  firmware/Core/Inc/adcs_drivers/adcs_command_ids.h
  firmware/Core/Inc/adcs_drivers/adcs_commands.h
  firmware/Core/Inc/adcs_drivers/adcs_internal_drivers.h
  firmware/Core/Inc/adcs_drivers/adcs_types.h
  firmware/Core/Inc/telecommands/telecommand_adcs.h
  firmware/Core/Src/adcs_drivers/adcs_commands.c
  firmware/Core/Src/adcs_drivers/adcs_internal_drivers.c
  firmware/Core/Src/telecommands/telecommand_adcs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: pr-please-review

#336 fix: GNSS buffer overrun, `rx_buf_len_dest` assignment
  docs/C_Namespaces.md
  firmware/Core/Inc/gps/gps_internal_drivers.h
  firmware/Core/Src/adcs_drivers/adcs_commands.c
  firmware/Core/Src/gps/gps_internal_drivers.c
  firmware/Core/Src/telecommands/gps_telecommand_defs.c
Labels: pr-please-review

#193 Boom experiment drivers and telecommands
  firmware/Core/Inc/boom_deploy_drivers/boom_deploy_drivers.h
  firmware/Core/Inc/telecommands/boom_deploy_telecommand_defs.h
  firmware/Core/Src/boom_deploy_drivers/boom_deploy_drivers.c
  firmware/Core/Src/telecommands/boom_deploy_telecommand_defs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: pr-don't-review-yet, pr-awaiting-testing

#349 fix: Prevent LFS formatting if LFS is mounted
  firmware/Core/Src/littlefs/littlefs_helper.c
Labels: quick

#348 Disable Non-Default EPS Channels on Boot
  firmware/Core/Inc/system/system_bootup.h
  firmware/Core/Src/main.c
  firmware/Core/Src/system/system_bootup.c
  firmware/Core/Src/uart_handler/uart_handler.c
Labels: pr-awaiting-testing

#369 Rename `json_output_str_len` to `json_output_str_size`
  firmware/Core/Inc/adcs_drivers/adcs_types_to_json.h
  firmware/Core/Inc/eps_drivers/eps_types_to_json.h
  firmware/Core/Src/adcs_drivers/adcs_types_to_json.c
  firmware/Core/Src/eps_drivers/eps_types_to_json.c
Labels: pr-please-review
