Repository CalgaryToSpace/CTS-SAT-1-OBC-Firmware, pull requests merged in 2025-03, with the labels that each got.

#278 Create int64_to_str function
  firmware/Core/Inc/transforms/arrays.h
  firmware/Core/Inc/unit_tests/test_byte_transforms.h
  firmware/Core/Src/transforms/arrays.c
  firmware/Core/Src/unit_tests/test_byte_transforms.c
  firmware/Core/Src/unit_tests/unit_test_inventory.c
Labels: quick, pr-please-review

#275 TCMD for retrieving battery voltage percent from PBU
  firmware/Core/Inc/eps_drivers/eps_calculations.h
  firmware/Core/Inc/telecommands/eps_telecommands.h
  firmware/Core/Inc/unit_tests/test_eps_calculations.h
  firmware/Core/Src/eps_drivers/eps_calculations.c
  firmware/Core/Src/telecommands/eps_telecommands.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
  firmware/Core/Src/unit_tests/test_eps_calculations.c
  firmware/Core/Src/unit_tests/unit_test_inventory.c
  firmware/STM32-for-VSCode.config.yaml
Labels: requirement, blocker, pr-please-review, pr-awaiting-testing

#279 Fix VS Code `launch.json` - debugging bug
  firmware/.vscode/launch.json
Labels: quick, pr-please-review

#280 LittleFS library upgraded to v2.10.1 (0494ce7)
  firmware/Core/Inc/littlefs/lfs.h
  firmware/Core/Inc/littlefs/lfs_util.h
  firmware/Core/Src/littlefs/lfs.c
Labels: quick, pr-please-review

#272 Send arbitrary bytes to UART peripheral, and read its response
  docs/Non-Critical_Notes/UART_Ports.md
  firmware/Core/Inc/log/log.h
  firmware/Core/Inc/mpi/mpi_command_handling.h
  firmware/Core/Inc/telecommands/uart_telecommand_defs.h
  firmware/Core/Inc/uart_handler/uart_handler.h
  firmware/Core/Src/log/log.c
  firmware/Core/Src/mpi/mpi_command_handling.c
  firmware/Core/Src/telecommands/mpi_telecommand_defs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
  firmware/Core/Src/telecommands/uart_telelecommand_defs.c
  firmware/Core/Src/uart_handler/uart_handler.c
  hardware_emulators/MPI_Emulator.py
Labels: pr-awaiting-testing

#255 Telecommands to Jump to Golden Copy and Switch Active Flash Bank
  docs/Non-Critical_Notes/Deployment_Final_Checks.md
  docs/Testing_Steps_for_Jumping_to_Golden_Copy.md
  docs/assets/Cube_Programmer_Step_1.png
  docs/assets/Cube_Programmer_Step_2.png
  docs/assets/Cube_Programmer_Step_3.png
  docs/assets/Modify_Heartbeat.png
  docs/assets/TCMD_Output.png
  firmware/Core/Inc/stm32_internal_flash_drivers/stm32_internal_flash_drivers.h
  firmware/Core/Inc/telecommands/stm32_internal_flash_telecommand_defs.h
  firmware/Core/Src/stm32_internal_flash_drivers/stm32_internal_flash_drivers.c
  firmware/Core/Src/system_stm32l4xx.c
  firmware/Core/Src/telecommands/stm32_internal_flash_telecommand_defs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: pr-please-review

#276 GPS ASCII Parsers and Unit Tests
  firmware/Core/Inc/gps/gps_ascii_parsers.h
  firmware/Core/Inc/gps/gps_types.h
  firmware/Core/Inc/transforms/arrays.h
  firmware/Core/Inc/unit_tests/unit_test_gps.h
  firmware/Core/Src/gps/gps_ascii_parsers.c
  firmware/Core/Src/gps/gps_types.c
  firmware/Core/Src/unit_tests/unit_test_gps.c
  firmware/Core/Src/unit_tests/unit_test_inventory.c
Labels: pr-please-review
