Repository CalgaryToSpace/CTS-SAT-1-OBC-Firmware, pull requests merged in 2025-02, with the labels that each got.

#215 ADCS commissioning
  docs/00_Getting_Started.md
  docs/40_Logging.md
  firmware/Core/Inc/adcs_drivers/adcs_command_ids.h
  firmware/Core/Inc/adcs_drivers/adcs_commands.h
  firmware/Core/Inc/adcs_drivers/adcs_internal_drivers.h
  firmware/Core/Inc/adcs_drivers/adcs_struct_packers.h
  firmware/Core/Inc/adcs_drivers/adcs_types.h
  firmware/Core/Inc/adcs_drivers/adcs_types_to_json.h
  firmware/Core/Inc/telecommands/telecommand_adcs.h
  firmware/Core/Inc/unit_tests/test_adcs.h
  firmware/Core/Src/adcs_drivers/adcs_commands.c
  firmware/Core/Src/adcs_drivers/adcs_internal_drivers.c
  firmware/Core/Src/adcs_drivers/adcs_struct_packers.c
  firmware/Core/Src/adcs_drivers/adcs_types_to_json.c
  firmware/Core/Src/telecommands/telecommand_adcs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
  firmware/Core/Src/unit_tests/test_adcs.c
  firmware/Core/Src/unit_tests/unit_test_inventory.c
Labels: pr-please-review

#216 LFS Telecommand to list files / directories [Issue #7]
  README.md
  firmware/Core/Inc/config/static_config.h
  firmware/Core/Inc/littlefs/littlefs_helper.h
  firmware/Core/Inc/telecommands/lfs_telecommand_defs.h
  firmware/Core/Src/littlefs/flash_driver.c
  firmware/Core/Src/littlefs/littlefs_driver.c
  firmware/Core/Src/littlefs/littlefs_helper.c
  firmware/Core/Src/telecommands/lfs_telecommand_defs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: blocker, pr-awaiting-changes

#263 Add `TCMD_require_unique_tssent` config variable to control whether tssent is required
  docs/Non-Critical_Notes/Configuration_Variables.md
  firmware/Core/Inc/config/configuration.h
  firmware/Core/Src/config/configuration.c
  firmware/Core/Src/telecommands/telecommand_executor.c
  firmware/Core/Src/unit_tests/test_telecommand_parser.c
Labels: bug, blocker, pr-awaiting-changes

#233 Telecommand: LFS delete file (#227)
  firmware/Core/Inc/telecommands/lfs_telecommand_defs.h
  firmware/Core/Src/telecommands/lfs_telecommand_defs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: command
