Repository CalgaryToSpace/CTS-SAT-1-OBC-Firmware, pull requests merged in 2025-05, with the labels that each got.

#368 Telecommand to get state of RBF pin
  firmware/Core/Inc/system/obc_internal_drivers.h
  firmware/Core/Inc/telecommands/system_telecommand_defs.h
  firmware/Core/Src/system/obc_internal_drivers.c
  firmware/Core/Src/telecommands/system_telecommand_defs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: pr-awaiting-testing

#374 LFS success log messages are the wrong level. Changed to normal.
  firmware/Core/Src/littlefs/littlefs_helper.c
Labels: pr-please-review, pr-awaiting-testing

#370 Count UART errors in `HAL_UART_ErrorCallback`
  firmware/Core/Inc/telecommands/uart_error_tracking_telecommands.h
  firmware/Core/Inc/uart_handler/uart_error_tracking.h
  firmware/Core/Inc/unit_tests/test_uart_error_tracking.h
  firmware/Core/Src/telecommands/telecommand_definitions.c
  firmware/Core/Src/telecommands/uart_error_tracking_telecommands.c
  firmware/Core/Src/uart_handler/uart_error_tracking.c
  firmware/Core/Src/uart_handler/uart_handler.c
  firmware/Core/Src/unit_tests/test_uart_error_tracking.c
  firmware/Core/Src/unit_tests/unit_test_inventory.c
Labels: pr-please-review, pr-awaiting-testing

#379 ADCS: Free up some unused telecommands
  firmware/Core/Inc/telecommands/telecommand_adcs.h
  firmware/Core/Src/adcs_drivers/adcs_commands.c
  firmware/Core/Src/telecommands/telecommand_adcs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: nice to have, command, quick, pr-please-review

#390 Send `LOG_message` calls over AX100 radio
  firmware/Core/Inc/comms_drivers/comms_tx.h
  firmware/Core/Inc/log/log.h
  firmware/Core/Src/comms_drivers/ax100_tx.c
  firmware/Core/Src/comms_drivers/comms_tx.c
  firmware/Core/Src/debug_tools/debug_uart.c
  firmware/Core/Src/log/log.c
  firmware/Core/Src/log/log_sinks.c
  firmware/Core/Src/main.c
  firmware/Core/Src/telecommand_exec/telecommand_executor.c
Labels: pr-awaiting-testing

#391 Telecommand: Read VBAT voltage with ADC
  firmware/Core/Inc/main.h
  firmware/Core/Inc/obc_systems/adc_vbat_monitor.h
  firmware/Core/Inc/telecommands/obc_systems_telecommand_defs.h
  firmware/Core/Src/obc_systems/adc_vbat_monitor.c
  firmware/Core/Src/telecommands/eps_telecommands.c
  firmware/Core/Src/telecommands/obc_systems_telecommand_defs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: pr-awaiting-changes

#396 ADCS: Create TCMD to erase ADCS SD file
  firmware/Core/Inc/adcs_drivers/adcs_commands.h
  firmware/Core/Inc/telecommands/telecommand_adcs.h
  firmware/Core/Src/adcs_drivers/adcs_commands.c
  firmware/Core/Src/telecommands/telecommand_adcs.c
  firmware/Core/Src/telecommands/telecommand_definitions.c
Labels: command

#414 Fix: JSON Format of core system stats
  firmware/Core/Src/telecommands/system_telecommand_defs.c
Labels: pr-awaiting-testing

#425 fix: Add power control to GNSS self-check
  firmware/Core/Src/gps/gps_internal_drivers.c
  firmware/Core/Src/self_checks/complete_self_check.c
  firmware/Core/Src/uart_handler/uart_handler.c
Labels: pr-awaiting-testing

#459 ADCS: Docstring fix
  firmware/Core/Inc/adcs_drivers/adcs_commands.h
  firmware/Core/Inc/adcs_drivers/adcs_types.h
  firmware/Core/Src/adcs_drivers/adcs_commands.c
  firmware/Core/Src/adcs_drivers/adcs_struct_packers.c
  firmware/Core/Src/adcs_drivers/adcs_types_to_json.c
  firmware/Core/Src/telecommands/telecommand_adcs.c
  firmware/Core/Src/unit_tests/test_adcs.c
Labels: documentation, nice to have, pr-please-review

#460 ADCS: Additional bootloader bugfix
  firmware/Core/Src/adcs_drivers/adcs_commands.c
Labels: bug, command, pr-please-review
